// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzY18dhoSfEodSsONW5q3b8OykqGWbkCk',
    appId: '1:523313211874:web:1c86b3cb30fa0f3a2d71bb',
    messagingSenderId: '523313211874',
    projectId: 'guy-of-warwick',
    authDomain: 'guy-of-warwick.firebaseapp.com',
    storageBucket: 'guy-of-warwick.firebasestorage.app',
    measurementId: 'G-VZQZ930ZH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBQK8dAx-kDffzK48wGGYsQAtogqAMeA',
    appId: '1:523313211874:android:c77e70d7d9f0886a2d71bb',
    messagingSenderId: '523313211874',
    projectId: 'guy-of-warwick',
    storageBucket: 'guy-of-warwick.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzY18dhoSfEodSsONW5q3b8OykqGWbkCk',
    appId: '1:523313211874:web:931daeb62a3b6e5d2d71bb',
    messagingSenderId: '523313211874',
    projectId: 'guy-of-warwick',
    authDomain: 'guy-of-warwick.firebaseapp.com',
    storageBucket: 'guy-of-warwick.firebasestorage.app',
    measurementId: 'G-VJV3EW8CCX',
  );
}
